competitions:
  respa:
    name:
      short:
        ru: "Республиканская олимпиада"
        kz: "Республикалық олимпиада"
      full:
        ru: "Республиканская олимпиада по предмету Физика"
        kz: "Физика пәні бойынша Республикалық олимпиада"
      stage:
        ru: "Заключительный этап"
        kz: "Қорытынды кезең"
    organizer:
      uppercase:
        ru: "РЕСПУБЛИКАНСКИЙ НАУЧНО-ПРАКТИЧЕСКИЙ ЦЕНТР «ДАРЫН»"
        kz: "«ДАРЫН» РЕСПУБЛИКАЛЫҚ ҒЫЛЫМИ-ПРАКТИКАЛЫҚ ОРТАЛЫҒЫ"
    grades: [9, 10, 11]
    languages: [ru, kz]
    tours:
      theory:
        name:
          ru: "Теоретический тур"
          kz: "Теориялық тур"
        duration_hours: 5
      experiment:
        name:
          ru: "Экспериментальный тур"
          kz: "Эксперименталдық тур"
        duration_hours: 3

  raion:
    name:
      ru: "Районная олимпиада"
    grades: [9, 10, 11]
    languages: [ru]
    tours:
      theory:
        duration_hours: 4

  oblast:

  junior_oblast:

  junior_respa:

  otbor_izho: