respa_junior:
  name:
    short:
      ru: "Республиканская олимпиада"
      kz: "Республикалық олимпиада"
    full:
      ru: "Республиканская юниорская олимпиада по предмету Физика"
      kz: "Физика пәнi бойынша жасөспiрiмдер арасындағы Республикалық олимпиада"
    stage:
      oblast:
        ru: "Областной этап"
        kz: "Облыстық кезең"
      final:
        ru: "Заключительный этап"
        kz: "Қорытынды кезең"
  organizer:
    normal:
      ru: "Республиканский Научно-Практический Центр <<Дарын>>"
      kz: "<<Дарын>> Республикалық Ғылыми-Практикалық Орталығы"
    uppercase:
      ru: "РЕСПУБЛИКАНСКИЙ НАУЧНО-ПРАКТИЧЕСКИЙ ЦЕНТР «ДАРЫН»"
      kz: "«ДАРЫН» РЕСПУБЛИКАЛЫҚ ҒЫЛЫМИ-ПРАКТИКАЛЫҚ ОРТАЛЫҒЫ"
  grades: [7, 8]
  languages: [ru, kz]
  instructions: true
  tours:
    theory:
      name:
        normal:
          ru: "Теоретический тур"
          kz: "Теориялық тур"
        lowercase:
          ru: "теоретический тур"
          kz: "теориялық тур"
      duration:
        final: 4
        oblast: 4
      problem_count:
        final: 4
        oblast: 4