respa:
  name:
    full:
      ru: "Республиканская олимпиада по предмету Физика"
      kz: "Физика пәні бойынша Республикалық олимпиада"
    raion:
      short:
        ru: "Районная олимпиада"
        kz: "Аудандық олимпиада"
      stage:
        ru: "Районный этап"
        kz: "Аудандық кезең"
    oblast:
      short:
        ru: "Областная олимпиада"
        kz: "Облыстық олимпиада"
      stage:
        ru: "Областной этап"
        kz: "Облыстық кезең"
    final:
      short:
        ru: "Республиканская олимпиада"
        kz: "Республикалық олимпиада"
      stage:
        ru: "Заключительный этап"
        kz: "Қорытынды кезең"
  organizer:
    normal:
      ru: "Республиканский Научно-Практический Центр <<Дарын>>"
      kz: "<<Дарын>> Республикалық Ғылыми-Практикалық Орталығы"
    uppercase:
      ru: "РЕСПУБЛИКАНСКИЙ НАУЧНО-ПРАКТИЧЕСКИЙ ЦЕНТР <<ДАРЫН>>"
      kz: "<<ДАРЫН>> РЕСПУБЛИКАЛЫҚ ҒЫЛЫМИ-ПРАКТИКАЛЫҚ ОРТАЛЫҒЫ"
  grades: [9, 10, 11]
  languages: [ru, kz]
  has_instructions: true
  tours:
    theory:
      name:
        normal:
          ru: "Теоретический тур"
          kz: "Теориялық тур"
        lowercase:
          ru: "теоретический тур"
          kz: "теориялық тур"
      duration:
        final: 5
        oblast: 4
        raion: 2
      problem_count:
        final: 3
        oblast: 4
        raion: 4
      has_experiment:
        final: true
        oblast: true
        raion: false
    experiment:
      name:
        normal:
          ru: "Экспериментальный тур"
          kz: "Эксперименталдық тур"
        lowercase:
          ru: "экспериментальный тур"
          kz: "эксперименталдық тур"
      duration:
        oblast: 2
        final: 3
      problem_count: 1